/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.ipr.app;

import ru.multithrading.ThreadTest;

public class App {

    public static void main(String[] args) {

        new ThreadTest().start();
        System.out.println("HELLO WORLD!!!");


    }

}
