/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.ipr.app;

import ru.ipr.pointOfEntry.MainApp;

public class App {

    public static void main(String[] args) {
        MainApp main = new MainApp();
    }

}
